# Generated by Django 2.0 on 2018-04-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180427_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='polls.Poll', verbose_name='Poll'),
        ),
    ]
