# Generated by Django 2.0 on 2018-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180427_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_index',
            field=models.IntegerField(default=1),
        ),
    ]
