# Generated by Django 2.0 on 2018-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180427_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='admission_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
