# Generated by Django 2.0 on 2018-05-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_poll_admission_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='page',
        ),
    ]
