# Generated by Django 2.0 on 2018-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180507_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
