# Generated by Django 2.0 on 2018-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180516_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='passed_poll',
            field=models.IntegerField(default=0),
        ),
    ]
