# Generated by Django 2.0 on 2018-05-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_pollstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
